<?php

/**
 * @file
 * An API for creating fillable, persistent checklists.
 *
 * Provides an interface for creating checklists that track progress with
 * completion times and users.
 */

/**
 * Link should always be shown.
 */
define('CHECKLISTAPI_LINK_CONTEXT_ANY', 1);

/**
 * Link should only be shown if the item it belongs to has been checked off.
 */
define('CHECKLISTAPI_LINK_CONTEXT_ITEM_CHECKED', 2);

/**
 * Link should only be shown if the item it belongs to has not been checked off.
 */
define('CHECKLISTAPI_LINK_CONTEXT_ITEM_UNCHECKED', 3);

/**
 * Access callback: Checks the current user's access to a checklist.
 *
 * @param string $id
 *   The checklist ID.
 * @param string $operation
 *   The operation to test access for. Possible values are "view", "edit", and
 *   "any". Defaults to "any".
 *
 * @return bool
 *   Returns TRUE if the current user has access to perform a given operation on
 *   the specified checklist, or FALSE if not.
 */
function checklistapi_checklist_access($id, $operation = 'any') {
  $view_access = user_access('view any checklistapi checklist') || user_access('view ' . $id . ' checklistapi checklist');
  $edit_access = user_access('edit any checklistapi checklist') || user_access('edit ' . $id . ' checklistapi checklist');
  switch ($operation) {
    case 'view':
      return $view_access;
    case 'edit':
      return $edit_access;
    case 'any':
    default:
      return $view_access || $edit_access;
  }
}

/**
 * Loads a checklist object.
 *
 * @param string $id
 *   The checklist ID.
 *
 * @return ChecklistapiChecklist|false
 *   A fully-loaded checklist object, or FALSE if the checklist is not found.
 */
function checklistapi_checklist_load($id) {
  $definition = checklistapi_get_checklist_info($id);
  return ($definition) ? new ChecklistapiChecklist($definition) : FALSE;
}

/**
 * Converts a string to lowerCamel case, suitably for a class property name.
 *
 * @param string $string
 *   The input string.
 *
 * @return string
 *   The input string converted to camelCase.
 */
function checklistapi_convert_string_to_lower_camel($string) {
  $string = str_replace('_', ' ', $string);
  $string = ucwords($string);
  $string = str_replace(' ', '', $string);
  return lcfirst($string);
}

/**
 * Gets checklist definitions.
 *
 * @param string $id
 *   (optional) A checklist ID.
 *
 * @return array|false
 *   The definition of the specified checklist, or FALSE if no such checklist
 *   exists, or an array of all checklist definitions if none is specified.
 */
function checklistapi_get_checklist_info($id = NULL) {
  $checklists = &drupal_static(__FUNCTION__);
  if (!isset($checklists)) {
    $checklists = module_invoke_all('checklistapi_checklist_info');
    $checklists = checklistapi_sort_array($checklists);
    drupal_alter('checklistapi_checklist_info', $checklists);
    $checklists = checklistapi_sort_array($checklists);
    foreach ($checklists as $key => $value) {
      $checklists[$key] = array('#id' => $key) + $checklists[$key];
    }
  }
  if (!empty($id)) {
    return (!empty($checklists[$id])) ? $checklists[$id] : FALSE;
  }
  return $checklists;
}

/**
 * Implements hook_help().
 */
function checklistapi_help($path, $arg) {
  $checklists = checklistapi_get_checklist_info();
  foreach ($checklists as $checklist) {
    if ($checklist['#path'] == $path && !empty($checklist['#help'])) {
      return $checklist['#help'];
    }
  }
}

/**
 * Implements hook_menu().
 */
function checklistapi_menu() {
  $items = array();
  // Checklists report.
  $items['admin/reports/checklistapi'] = array(
    'title' => 'Checklists',
    'page callback' => 'checklistapi_report_form',
    'access arguments' => array('view checklistapi checklists report'),
    'description' => 'Get an overview of your installed checklists with progress details.',
    'file' => 'checklistapi.admin.inc',
  );
  // Individual checklists.
  foreach (checklistapi_get_checklist_info() as $checklist_id => $checklist) {
    if (!empty($checklist['#path']) && !empty($checklist['#title'])) {
      $checklist_path = $checklist['#path'];
      // View/edit checklist.
      $items[$checklist_path] = array(
        'title' => $checklist['#title'],
        'description' => (!empty($checklist['#description'])) ? $checklist['#description'] : '',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('checklistapi_checklist_form', $checklist_id),
        'access callback' => 'checklistapi_checklist_access',
        'access arguments' => array($checklist_id),
        'file' => 'checklistapi.pages.inc',
        'menu_name' => (!empty($checklist['#menu_name'])) ? $checklist['#menu_name'] : '',
      );
      // Clear saved progress.
      $items[$checklist_path . '/clear'] = array(
        'title' => 'Clear',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('checklistapi_checklist_clear_confirm', $checklist_id),
        'access callback' => 'checklistapi_checklist_access',
        'access arguments' => array($checklist_id, 'edit'),
        'file' => 'checklistapi.pages.inc',
      );
    }
  }
  return $items;
}

/**
 * Implements hook_permission().
 */
function checklistapi_permission() {
  $perms = array();
  // Universal permissions.
  $perms['view checklistapi checklists report'] = array(
    'title' => t(
      'View the !name report',
      array('!name' => (user_access('view checklistapi checklists report')) ? l(t('Checklists'), 'admin/reports/checklistapi') : drupal_placeholder('Checklists'))
    ),
  );
  $perms['view any checklistapi checklist'] = array(
    'title' => t('View any checklist'),
    'description' => $view_checklist_perm_description = t('Read-only access: View list items and saved progress.'),
  );
  $perms['edit any checklistapi checklist'] = array(
    'title' => t('Edit any checklist'),
    'description' => $edit_checklist_perm_description = t('Check and uncheck list items and save changes, or clear saved progress.'),
  );
  // Per checklist permissions.
  foreach (checklistapi_get_checklist_info() as $id => $checklist) {
    if (!empty($id)) {
      $perms['view ' . $id . ' checklistapi checklist'] = array(
        'title' => t(
          'View the !name checklist',
          array('!name' => (checklistapi_checklist_access($id)) ? l($checklist['#title'], $checklist['#path']) : drupal_placeholder($checklist['#title']))
        ),
        'description' => $view_checklist_perm_description,
      );
      $perms['edit ' . $id . ' checklistapi checklist'] = array(
        'title' => t(
          'Edit the !name checklist',
          array('!name' => (checklistapi_checklist_access($id)) ? l($checklist['#title'], $checklist['#path']) : drupal_placeholder($checklist['#title']))
        ),
        'description' => $edit_checklist_perm_description,
      );
    }
  }
  return $perms;
}

/**
 * Recursively sorts array elements by #weight.
 *
 * @param array $array
 *   A nested array of elements and properties, such as the checklist
 *   definitions returned by hook_checklistapi_checklist_info().
 *
 * @return array
 *   The input array sorted recursively by #weight.
 *
 * @see checklistapi_get_checklist_info()
 */
function checklistapi_sort_array(array $array) {
  $child_keys = element_children($array);
  if (count($child_keys)) {
    $incrementer = 0;
    $children = array();
    foreach ($child_keys as $key) {
      // Move child to a temporary array for sorting.
      $children[$key] = $array[$key];
      unset($array[$key]);
      // Supply a default weight if missing or invalid.
      if (empty($children[$key]['#weight']) || !is_numeric($children[$key]['#weight'])) {
        $children[$key]['#weight'] = 0;
      }
      // Increase each weight incrementally to preserve the original order when
      // not overridden. This accounts for undefined behavior in PHP's uasort()
      // function when its comparison callback finds two values equal.
      $children[$key]['#weight'] += ($incrementer++ / 1000);
      // Descend into child.
      $children[$key] = checklistapi_sort_array($children[$key]);
    }
    // Sort by weight.
    uasort($children, 'element_sort');
    // Remove incremental weight hack.
    foreach ($children as $key => $child) {
      $children[$key]['#weight'] = floor($children[$key]['#weight']);
    }
    // Put children back in the main array.
    $array += $children;
  }
  return $array;
}
